### ISSUE TITLE
Загрузка тестур на карты "Ложных богов" в TTS 

### ISSUE THREAD

**Issue by old-coot** [SkAZi/berserk-nxt#2]
Добрый день. При импорте колоды из веб версии  в TTS возникает ошибка. С другими сетами все ок. Заранее спасибо
<img width="311" alt="tts" src="https://github.com/user-attachments/assets/0a2ee1cb-b981-4428-aeca-faee929a6506">

**Comment by SkAZi** [comment]
Должно быть поправлено, спасибо!
