### ISSUE TITLE
Черные карты при импорте в TTS

### ISSUE THREAD

**Issue by old-coot** [SkAZi/berserk-nxt#3]
Карты отображаются черным цветом при импорте из веб версии в ТТS.
![image](https://github.com/user-attachments/assets/01369c18-f410-4600-8425-880f07dec485)

Список черных карт:
Мастер осад
Орочья пушка
Требушет
Колесница Аккении
Дирр
Дирр-гигант

Заранее спасибо

**Comment by SkAZi** [comment]
До полного выхода 4 сета периодически будут подобные штуки, в силу кешей TTS, можно чистить, что-то будет добавляться. Полный сет уже совсем скоро, тогда всё нормализуется окончательно.

**Comment by old-coot** [comment]
Спасибо. Тогда закрываем
