### ISSUE TITLE
отсутствует ПФ карта Кирин

### ISSUE THREAD

**Issue by WolfAvenger** [SkAZi/berserk-nxt#4]
Не обнаружил среди всех карт полноформатную карту "Кирин"
![photo_2024-09-29_20-36-16](https://github.com/user-attachments/assets/2216f2e7-a05f-4c12-8e08-29bce0beaf59)

**Comment by WolfAvenger** [comment]
![photo_2024-09-29_20-39-29](https://github.com/user-attachments/assets/62e397a3-c9fe-4e71-9b67-d2b9f5dfda19)
и "Проклятый доспех" ПФ

**Comment by SkAZi** [comment]
Промки выкладываются разработчиками постепенно, по мере турнирных сезонов и несомненно будут добавляться, только с некоторым опозданием. Т.к. делать пересборку на каждые 2 карты достаточно затруднительно.
